# Generated by Django 4.0.4 on 2022-06-20 07:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mqtt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('auto', 'AUTO. Автоматический режим'), ('eco', 'ECO. Экономичный режим'), ('turbo', 'TURBO. Турбо'), ('cool', 'COOL. Охлаждение'), ('dry', 'DRY. Режим осушения'), ('fan_only', 'FAN_ONLY. Вентиляция'), ('heat', 'HEAT. Обогрев'), ('preheat', 'PREHEAT. Подогрев, [разогрев, предварительный нагрев, предварительный разогрев]'), ('high', 'HIGH. Высокая скорость'), ('low', 'LOW. Низкая скорость'), ('medium', 'MEDIUM. Средняя скорость'), ('max', 'MAX. Максимальный, [максимум]'), ('min', 'MIN. Минимальный, [минимум]'), ('fast', 'FAST. Быстрый'), ('slow', 'SLOW. Медленный'), ('express', 'EXPRESS. Экспресс'), ('normal', 'NORMAL. Нормальный, [обычный]'), ('quiet', 'QUIET. Тихий, [ночной]'), ('horizontal', 'HORIZONTAL. Горизонтальный'), ('stationary', 'STATIONARY. Неподвижный, [статичный, фиксированный]'), ('vertical', 'VERTICAL. Вертикальный'), ('one', 'ONE. Первый'), ('two', 'TWO. Второй'), ('three', 'THREE Третий'), ('four', 'FOUR. Четвёртый'), ('five', 'FIVE. Пятый'), ('six', 'SIX. Шестой'), ('seven', 'SEVEN. Седьмой'), ('eight', 'EIGHT. Восьмой'), ('nine', 'NINE. Девятый'), ('ten', 'TEN. Десятый'), ('americano', 'AMERICANO. Американо'), ('cappuccino', 'CAPPUCCINO. Капучино'), ('double_espresso', 'DOUBLE_ESPRESSO. Двойной эспрессо'), ('espresso', 'ESPRESSO. Эспрессо'), ('latte', 'LATTE. Латте'), ('black_tea', 'BLACK_TEA. Черный чай'), ('flower_tea', 'FLOWER_TEA. Цветочный чай'), ('green_tea', 'GREEN_TEA. Зеленый чай'), ('herbal_tea', 'HERBAL_TEA. Травяной чай'), ('oolong_tea', 'OOLONG_TEA. Чай улун'), ('puerh_tea', 'PUERH_TEA. Чай пуэр'), ('red_tea', 'RED_TEA. Красный чай'), ('white_tea', 'WHITE_TEA. Белый чай'), ('glass', 'GLASS. Мойка стекла'), ('intensive', 'INTENSIVE. Интенсивный'), ('pre_rinse', 'PRE_RINSE. Ополаскивание'), ('aspic', 'ASPIC. Холодец'), ('baby_food', 'BODY_FOOD. Детское питание'), ('baking', 'BAKING. Выпечка'), ('bread', 'BREAD. Хлеб'), ('boiling', 'BOOLING. Варка'), ('cereals', 'CEREALS. Крупы'), ('cheesecake', 'CHEESECAKE. Чизкейк'), ('deep_fryer', 'DEEP_FRYER. Фритюр'), ('dessert', 'DESSERT. Десерты'), ('fowl', 'FOWL. Дичь'), ('frying', 'FRYING. Жарка'), ('macaroni', 'MACARONI. Макароны'), ('milk_porridge', 'MILK_PORRIDGE. Молочная каша'), ('multicooker', 'MULTICOOKER. Мультиповар'), ('pasta', 'PASTA. Паста'), ('pilaf', 'PILAF. Плов'), ('pizza', 'PIZZA. Пицца'), ('sauce', 'SAUCE. Соус'), ('slow_cook', 'SLOW_COOK. Томление'), ('soup', 'SOUP. Суп'), ('steam', 'STEAM. Пар'), ('stewing', 'STEWING. Тушение'), ('vacuum', 'VACUUM. Вакуум'), ('yogurt', 'YOGURT. Йогурт')], max_length=50, verbose_name='mode')),
            ],
            options={
                'verbose_name': 'функция(Mode) умения',
                'verbose_name_plural': 'функции(Mode) умения',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'комната',
                'verbose_name_plural': 'комнаты',
            },
        ),
        migrations.CreateModel(
            name='YandexDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('oauth_token', models.CharField(help_text='https://yandex.ru/dev/dialogs/smart-home/doc/reference-alerts/resources-alerts.html#resources-alerts__oauth', max_length=40, verbose_name='OAuth токен')),
                ('skill_id', models.UUIDField(help_text='https://dialogs.yandex.ru/developer/skills/{skill_id}', verbose_name='ID навыка в яндексе')),
            ],
            options={
                'verbose_name': 'яндекс диалог',
                'verbose_name_plural': 'яндекс диалоги',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('devices.types.light', 'LIGHT. Устройство, которое имеет управляемые светящиеся элементы'), ('devices.types.socket', 'SOCKET. Розетка'), ('devices.types.switch', 'SWITCH. Выключатель'), ('devices.types.thermostat', 'THERMOSTAT. Устройство с возможностью регулирования температуры'), ('devices.types.thermostat.ac', 'THERMOSTAT_AC. Устройство, управляющее микроклиматом в помещении, с возможностью регулирования температуры и режима работы'), ('devices.types.media_device', 'MEDIA_DEVICE. Аудио, видео, мультимедиа техника. Устройства, которые умеют воспроизводить звук и видео. Аудио, видео, мультимедиа техника. Устройства, которые умеют воспроизводить звук и видео'), ('devices.types.media_device.tv', 'TV. Устройство для просмотра видеоконтента. На устройстве можно изменять громкость и переключать каналы'), ('devices.types.media_device.tv_box', 'TV_BOX. Устройство, подключаемое к телевизору или дисплею, для просмотра видеоконтента. На устройстве можно управлять громкостью воспроизведения и переключать каналы'), ('devices.types.media_device.receiver', 'RECEIVER. Устройство, подключаемое к телевизору или дисплею, для просмотра видеоконтента. На устройстве можно изменять громкость, переключать каналы и источники аудио-/видеосигнала'), ('devices.types.cooking', 'COOKING. Различная умная кухонная техника'), ('devices.types.cooking.coffee_maker', 'COFFEE_MAKER. Устройство, которое умеет делать кофе'), ('devices.types.cooking.kettle', 'KETTLE. Устройство, которое умеет кипятить воду и/или делать чай.'), ('devices.types.cooking.multicooker', 'MULTICOOKER. Устройство, которое выполняет функции мультиварки — приготовление пищи по заданным программам'), ('devices.types.openable', 'OPENABLE. Устройство, которое умеет открываться и/или закрываться'), ('devices.types.openable.curtain', 'CURTAIN. Устройство, которое выполняет функцию штор'), ('devices.types.humidifier', 'HUMIDIFIER. Устройство, которое умеет изменять влажность в помещении'), ('devices.types.purifier', 'PURIFIER. Устройство с функцией очистки воздуха'), ('devices.types.vacuum_cleaner', 'VACUUM_CLEANER. Устройство, которое выполняет функцию пылесоса'), ('devices.types.washing_machine', 'WASHING_MASHINE. Устройство для стирки белья'), ('devices.types.dishwasher', 'DISHWASHER. Устройство для мытья посуды'), ('devices.types.iron', 'IRON. Устройство, которое выполняет функции утюга'), ('devices.types.sensor', 'SENSOR. Устройство, которое передает данные со свойств'), ('devices.types.other', 'OTHER. Остальные устройства, не подходящие под типы выше')], help_text='https://yandex.ru/dev/dialogs/smart-home/doc/concepts/device-types.html', max_length=50, verbose_name='Тип')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Кастомные данные')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yandex.room', verbose_name='Комната')),
                ('yd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex.yandexdialog', verbose_name='Яндекс диалог (навык)')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'устройства',
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('devices.capabilities.on_off', 'ON_OFF. Удаленное включение и выключение устройства'), ('devices.capabilities.color_setting', 'COLOR_SETTING. Управление цветом для светящихся элементов в устройстве'), ('devices.capabilities.mode', 'MODE. Переключение режимов работы устройства, например, переключение между температурными режимами работы кондиционера'), ('devices.capabilities.range', 'RANGE. Управление параметрами устройства, которые имеют диапазон'), ('devices.capabilities.toggle', 'TOGGLE. Управление параметрами устройства, которые могут находиться только в одном из двух состояний'), ('devices.capabilities.video_stream', 'VIDEO_STREAM. Получение видеопотока с камеры')], max_length=100, verbose_name='Тип устройства')),
                ('parameters', models.JSONField(default=dict, editable=False, verbose_name='Параметры')),
                ('retrievable', models.BooleanField(default=True, help_text='Признак включенного оповещения об изменении состояния умения при помощи сервиса уведомлений', verbose_name='Включенное оповещение')),
                ('reportable', models.BooleanField(default=True, help_text='Доступен ли для данного умения устройства запрос состояния', verbose_name='Доступен ли запрос состояния')),
                ('state', models.JSONField(blank=True, default=list, help_text='Стейт')),
                ('command_topic', models.CharField(max_length=100, verbose_name='Топик для команд')),
                ('state_topic', models.CharField(max_length=100, verbose_name='Топик для состояния')),
                ('color_model', models.CharField(blank=True, choices=[('rgb', 'RGB'), ('hsv', 'HSV')], max_length=10, verbose_name='Цветовая модель')),
                ('temp_k_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная температура света')),
                ('temp_k_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная температура света')),
                ('mode_instance', models.CharField(blank=True, choices=[('cleanup_mode', 'CLEANUP_MODE. Установка режима уборки'), ('dishwashing', 'DISHWASHING. Установка режима мытья посуды'), ('fan_speed', 'FAN_SPEED. Установка режима работы скорости вентиляции, например, в кондиционере, вентиляторе или обогревателе'), ('heat', 'HEAT. Установка режима нагрева'), ('input_source', 'INPUT_SOURCE. Установка источника сигнала'), ('program', 'PROGRAM. Установка какой-либо программы работы'), ('swing', 'SWING. Установка направления воздуха в климатической технике'), ('tea_mode', 'TEA_MODE. Установка режима приготовления чая'), ('thermostat', 'THERMOSTAT. Установка температурного режима работы климатической техники, например, в кондиционере'), ('work_speed', 'WORK_SPEED. Установка скорости работы')], max_length=50, verbose_name='instance')),
                ('split', models.BooleanField(blank=True, help_text='За включение/выключение устройства у провайдера отвечают разные команды', verbose_name='split')),
                ('range_instance', models.CharField(blank=True, choices=[('brightness', 'BRIGHTNESS. Изменение яркости световых элементов'), ('channel', 'CHANNEL. Изменение канала, например телевизионного'), ('humidity', 'HUMIDITY. Изменение влажности'), ('open', 'OPEN. Открывание чего-либо (открывание штор, окна)'), ('temperature', 'TEMPERATURE. Изменение температуры. Может обозначать температуру нагрева чайника, обогревателя или температуру кондиционера в каком-либо его режиме'), ('volume', 'VOLUME. Изменение громкости устройства')], max_length=50, verbose_name='instance')),
                ('unit', models.CharField(blank=True, choices=[('unit.percent', 'Проценты'), ('unit.temperature.celsius', 'Цельсий'), ('unit.temperature.kelvin', 'Кельвины')], max_length=50, verbose_name='Единица измерения')),
                ('random_access', models.BooleanField(blank=True, help_text='Если эта возможность выключена, пользователю будет доступно только последовательное изменение значений — в большую или меньшую сторону. Например, изменение громкости телевизора при работе через ИК пульт.', verbose_name='Произвольные значения')),
                ('range_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальное значение')),
                ('range_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальное значение')),
                ('range_precision', models.PositiveIntegerField(blank=True, null=True, verbose_name='Шаг')),
                ('toggle_instance', models.CharField(blank=True, choices=[('backlight', 'BACKLIGHT. Подсветка'), ('controls_locked', 'CONTROLS_LOCKED. Детский режим'), ('ionization', 'IONIZATION. Ионизация'), ('keep_warm', 'KEEP_WARM. Поддержание тепла'), ('mute', 'MUTE. Выключение звука'), ('oscillation', 'OSCILLATION. Вращение'), ('pause', 'PAUSE. Пауза')], max_length=50, verbose_name='instance')),
                ('protocol', models.CharField(blank=True, choices=[('hls', 'HLS'), ('progressive_mp4', 'PROGRESSIVE_MP4')], max_length=50, verbose_name='Протокол')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='yandex.device', verbose_name='Устройство')),
                ('modes', models.ManyToManyField(blank=True, to='yandex.capabilitymode')),
                ('mqtt_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mqtt.mqttconfig', verbose_name='Конфигурация MQTT')),
            ],
            options={
                'verbose_name': 'умение',
                'verbose_name_plural': 'умения',
            },
        ),
    ]
