# Generated by Django 4.0.4 on 2022-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexdialog',
            name='oauth_token',
            field=models.CharField(help_text='https://yandex.ru/dev/dialogs/smart-home/doc/reference-alerts/resources-alerts.html#resources-alerts__oauth', max_length=40, verbose_name='OAuth токен'),
        ),
        migrations.AlterField(
            model_name='yandexdialog',
            name='skill_id',
            field=models.UUIDField(help_text='https://dialogs.yandex.ru/developer/skills/{skill_id}', verbose_name='ID навыка в яндексе'),
        ),
    ]
