# Generated by Django 4.0.4 on 2022-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль')),
                ('url', models.CharField(default='localhost', max_length=100, verbose_name='URL')),
                ('port', models.PositiveIntegerField(default=1883, verbose_name='Порт')),
            ],
            options={
                'verbose_name': 'Конфигурация MQTT',
                'verbose_name_plural': 'Конфигурации MQTT',
            },
        ),
    ]
